name = "kairos-crm"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://backend-production-33ef.up.railway.app"
NEXT_PUBLIC_SOCKET_URL = "https://backend-production-33ef.up.railway.app"
